<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="hp" failures="2" tests="2" name="Default test(failed)" time="0.082" errors="0" timestamp="24 Jul 2020 10:19:31 GMT">
  <testcase classname="listeners.Failurererun" name="test2" time="0.022">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at listeners.Failurererun.test2(Failurererun.java:18)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="listeners.Failurererun" name="test3" time="0.003">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at listeners.Failurererun.test3(Failurererun.java:25)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="listeners.Failurererun" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
